### ISSUE TITLE
Prune packages.nix

### ISSUE THREAD

**Issue by Fuuzetsu** [4e6/stackage2nix#19]
It is not necessary for packages.nix to list every single package in the LTS: only the packages that are dependencies or transitive dependencies of the projects in the given stack.yaml can be listed. This pruning can be pretty simple and does not have to be perfect: we can just use the argument sets as the set of dependencies even if some would be unused due to any flags in the expression itself.

This should allow a much nicer time when we check in packages.nix into code repository and more importantly, a much more meaningful diff when dependency set is updated: it will become clear what packages we added, updated or removed.

**Comment by 4e6** [comment]
I thought of it myself, this would be a very nice feature indeed.

Implementation (as a note to myself):
- Add flag `-[no]-packages-closure` to disable/enables feature
- `stackage2nix` already have a graph representation of Stack LTS package set. We need to implement some kind of DFS algorithm that by given initial set of vertices (packages) produces set of reachable ones (transitive dependencies).
